### PR TITLE
fix: Use project_name instead of removed repo_name field in health.rs

### PR DESCRIPTION
**Pull request by btucker**
## Summary

- Fixes compilation failure on main caused by `snap.repo_name` reference in `health.rs:1157`
- PR #1788 (Emit coworker.stuck workflow event) added code using `snap.repo_name`, but the field was renamed to `project_name`/`dir_key` in the earlier PR #1793 (Separate project_name from dir_key)
- The merge didn't catch this because it was a semantic clash, not a textual conflict — the code compiled against pre-refactor code but failed after both merged to main

## Test plan

- [x] `cargo clippy --all-targets --all-features -- -D warnings` passes locally
- [ ] CI passes (all E2E tests were failing due to this compilation error)

🌃 Co-built with [Midtown](https://github.com/btucker/midtown)

### CODE REVIEW

**Comment by btucker** [comment]
## Review Status

🔍 Review in progress by broadway...

---
> [!NOTE]
> This comment will be updated with the review results when complete.

🌃 Co-built with [Midtown](https://github.com/btucker/midtown)

**Comment by btucker** [comment]
### Code review

No issues found. Checked for bugs and CLAUDE.md compliance.

This is a clear one-line fix for a semantic merge conflict: `snap.repo_name` was renamed to `snap.project_name` in PR #1793, but PR #1788 added new code referencing the old field name. The fix correctly uses `snap.project_name`.

https://github.com/btucker/midtown/blob/7f6942eb50be8f7e79a57fddb2e5466823669f6d/src/daemon/health.rs#L1153-L1161

🌃 Co-built with [Midtown](https://github.com/btucker/midtown)

**Comment by btucker** [comment]
✅ No issues to address — broadway's review confirmed the fix is correct.

🌃 Co-built with [Midtown](https://github.com/btucker/midtown)
